import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import '../lib/i18n';
import { WalletProvider } from "@/lib/walletProvider";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <Suspense fallback={<div>Loading...</div>}>
       <WalletProvider>
          {children}
        </WalletProvider>
        </Suspense>
      </body>
    </html>
  );
}
